- hosts: kolide
  become: yes
  become_user: root
  tasks:
    - import_tasks: 'roles/kolide/init.yml'
    - import_tasks: 'roles/kolide/setup_redis.yml'
    - import_tasks: 'roles/kolide/setup_mysql.yml'
    - import_tasks: 'roles/kolide/setup_kolide.yml'
    - import_tasks: 'roles/kolide/setup_nginx.yml'