####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  timezone: 
    name: '{{ timezone }}'

####################################################################
# Set hostname
####################################################################
- name: change hostname to {{ kolide_hostname }}
  hostname:
    name: "{{ kolide_hostname }}"

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ kolide_hostname }}'
    state: present

####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  ufw:
    rule: allow
    name: OpenSSH
- ufw:
    rule: allow
    port: 80
    proto: tcp
- ufw:
    rule: allow
    port: 443
    proto: tcp
- ufw:
    logging: medium
- ufw:
    state: enabled
    policy: deny

####################################################################
#  Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Init setup - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined